name:                subsets
version:             0.1.0.0
github:              "felixlinker/subsets"
license:             MIT
author:              "Felix Linker"
maintainer:          "linkerfelix@gmail.com"
copyright:           "2019 Felix Linker"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/subsets#readme>

dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: src
